.TH CHECK_WKHTMLTOPDF 1 2022-04-07 "" "check the wkhtmltpdf config is valid or not"
.SH NAME
check_wkhtmltopdf \- check_wkhtmltopdf()
.SH SYNOPSIS
\fIcheck_wkhtmltopdf()\fR
.SH FILES
.PP
SMRUCC/R#.declare_function.check_wkhtmltopdf<$anonymous_09569> at utils.R:line 3
.PP
.SH COPYRIGHT
Copyright © Who wrote it, What license is it under? Licensed 2022
