.\" man page create by R# package system.
.TH HTMLREPORT 4 2000-Jan "countFigures" "countFigures"
.SH NAME
countFigures \- 
.SH SYNOPSIS
\fIcountFigures(\fBreport\fR as any, 
\fBorders\fR as string = \fB<NULL>\fR, 
\fBfigStart\fR as integer = 1, 
\fBprefix\fR as string = "fig", 
\fBformat\fR as string = "p #. ", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
htmlReport
.SH FILES
.PP
reportKit.dll
.PP
