.\" man page create by R# package system.
.TH HTMLREPORT 4 2000-1月 "flush" "flush"
.SH NAME
flush \- save the modified interpolated html
.SH SYNOPSIS
\fIflush(\fBtemplate\fR as <generic> HTMLReport, 
\fBoutputdir\fR as string = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
save the modified interpolated html
 template data onto the disk file.
.PP
.SH OPTIONS
.PP
\fBtemplate\fB \fR\- -. 
.PP
.PP
\fBoutputdir\fB \fR\- 
 export of the page files into this new output 
 directory instead of export to the source 
 folder where this report object is loaded via 
 the \fBreportTemplate\fR function.
. 
.PP
.SH SEE ALSO
htmlReport
.SH FILES
.PP
reportKit.dll
.PP
