.\" man page create by R# package system.
.TH HTMLREPORT 4 2000-1月 "htmlTemplate" "htmlTemplate"
.SH NAME
htmlTemplate \- Create a html template model from the given template file
.SH SYNOPSIS
\fIhtmlTemplate(\fBurl\fR as string);\fR
.SH DESCRIPTION
.PP
Create a html template model from the given template file
.PP
.SH OPTIONS
.PP
\fBurl\fB \fR\- should be a local file its file path, andalso this function also supports
 the http url for http get and load the template document text.. 
.PP
.SH SEE ALSO
htmlReport
.SH FILES
.PP
reportKit.dll
.PP
