.\" man page create by R# package system.
.TH HTMLREPORT 4 2000-Jan "html_render" "html_render"
.SH NAME
html_render \- 
.SH SYNOPSIS
\fIhtml_render(\fBimage_class\fR as string = \fB<NULL>\fR, 
\fBimage_url\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBimage_url\fB \fR\- 
 apply for the document template rendering
. 
.PP
.SH SEE ALSO
htmlReport
.SH FILES
.PP
reportKit.dll
.PP
