.\" man page create by R# package system.
.TH HTMLREPORT 4 2000-Jan "htmlTemplate" "htmlTemplate"
.SH NAME
htmlTemplate \- Create a html template model from the given template file
.SH SYNOPSIS
\fIhtmlTemplate(\fBurl\fR as string);\fR
.SH DESCRIPTION
.PP
Create a html template model from the given template file
.PP
.SH OPTIONS
.PP
\fBurl\fB \fR\- -. 
.PP
.SH SEE ALSO
htmlReport
.SH FILES
.PP
reportKit.dll
.PP
