.\" man page create by R# package system.
.TH HTMLREPORT 4 2000-Jan "interpolate" "interpolate"
.SH NAME
interpolate \- do report data interpolation.
.SH SYNOPSIS
\fIinterpolate(\fBtemplate\fR as <generic> HTMLReport, 
\fBmetadata\fR as list, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
do report data interpolation.
.PP
.SH OPTIONS
.PP
\fBtemplate\fB \fR\- -. 
.PP
.PP
\fBmetadata\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
htmlReport
.SH FILES
.PP
reportKit.dll
.PP
