.\" man page create by R# package system.
.TH HTMLREPORT 4 2000-1月 "interpolate.html" "interpolate.html"
.SH NAME
interpolate.html \- do report data interpolation.
.SH SYNOPSIS
\fIinterpolate.html(\fBtemplate\fR as <generic> TemplateHandler, 
\fBmetadata\fR as list, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
do report data interpolation.
.PP
.SH OPTIONS
.PP
\fBtemplate\fB \fR\- -. 
.PP
.PP
\fBmetadata\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
htmlReport
.SH FILES
.PP
reportKit.dll
.PP
