.\" man page create by R# package system.
.TH HTMLREPORT 4 2000-01-01 "loadResource" "loadResource"
.SH NAME
loadResource \- 
.SH SYNOPSIS
\fIloadResource(\fBdescription\fR as <generic> JsonObject, 
\fBworkdir\fR as any = CALL "GETWD"(), 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
htmlReport
.SH FILES
.PP
reportKit.dll
.PP
