.\" man page create by R# package system.
.TH HTMLREPORT 4 2000-Jan "loadResource" "loadResource"
.SH NAME
loadResource \- Load resource files for build html report
.SH SYNOPSIS
\fIloadResource(\fBdescription\fR as <generic> JsonObject, 
\fBworkdir\fR as any = CALL "GETWD"(), 
\fBmeta\fR as list = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Load resource files for build html report
 
 load the resource files based on the description list data, 
 and then generates the html segments for the resource files.
.PP
.SH OPTIONS
.PP
\fBdescription\fB \fR\- 
 the resource file contents in this description data 
 supports file types:
 
 1. \fB*.txt\fR for plant text file
 2. \fB*.csv\fR for data table file
 3. \fB*.png/jpg/bmp\fR for raster image file
 4. \fB*.svg\fR for vector image file
 5. \fB*.html\fR for html text file
 6. \fB*.md\fR for makrdown text file, the markdown text file 
      will be rendering as the html document text at first
      and then returns a html document to the rendering 
      engine.
      
. 
.PP
.PP
\fBworkdir\fB \fR\- -. 
.PP
.PP
\fBmeta\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
htmlReport
.SH FILES
.PP
reportKit.dll
.PP
