.\" man page create by R# package system.
.TH HTMLREPORT 4 2000-1月 "pageNumbers" "pageNumbers"
.SH NAME
pageNumbers \- assign the page numbers to the html templates
.SH SYNOPSIS
\fIpageNumbers(\fBreport\fR as <generic> HTMLReport, 
\fBorders\fR as string, 
\fBpageStart\fR as integer = 1, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
assign the page numbers to the html templates
.PP
.SH OPTIONS
.PP
\fBreport\fB \fR\- the html report template model. 
.PP
.PP
\fBorders\fB \fR\- 
 the file basename of the html files to sort of the pages inside the report model object.
. 
.PP
.PP
\fBpageStart\fB \fR\- 
 page number count start, default is count start from 1
. 
.PP
.SH DETAILS
.PP
the placeholder of the page number inside the template document text should be:
 
 1. [#page] for the page number of current page
 2. [#total_pages] for the total page numbers which is count from the template files.
.PP
.SH SEE ALSO
htmlReport
.SH FILES
.PP
reportKit.dll
.PP
