.\" man page create by R# package system.
.TH HTMLREPORT 4 2000-Jan "pageBreak" "pageBreak"
.SH NAME
pageBreak \- insert a pdf pagebreak div into the current html template string
.SH SYNOPSIS
\fIpageBreak();\fR
.SH DESCRIPTION
.PP
insert a pdf pagebreak div into the current html template string
.PP
.SH SEE ALSO
htmlReport
.SH FILES
.PP
reportKit.dll
.PP
