.\" man page create by R# package system.
.TH HTMLREPORT 4 2000-Jan "pageHeaders" "pageHeaders"
.SH NAME
pageHeaders \- assign the page headers to the html templates
.SH SYNOPSIS
\fIpageHeaders(\fBreport\fR as any, 
\fBorders\fR as string = \fB<NULL>\fR, 
\fBheaderStart\fR as string = "1", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
assign the page headers to the html templates
.PP
.SH OPTIONS
.PP
\fBreport\fB \fR\- -. 
.PP
.PP
\fBorders\fB \fR\- -. 
.PP
.PP
\fBheaderStart\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH DETAILS
.PP
place holder for the title could be:
 
 \fB[#h1]\fR, \fB[#h2]\fR, \fB[#h3]\fR and \fB[#h4]\fR.
.PP
.SH SEE ALSO
htmlReport
.SH FILES
.PP
reportKit.dll
.PP
