.\" man page create by R# package system.
.TH HIGHCHARTS.JS 1 2000-01-01 "barchart" "barchart"
.SH NAME
barchart \- 
.SH SYNOPSIS
\fIbarchart(\fBdata\fR as list, 
\fBtitle\fR as string = "title", 
\fBsubtitle\fR as string = "subtitle", 
\fBylab\fR as string = "Y", 
\fBserialName\fR as string = "data", 
\fBbackgroundColor\fR as any = "#ffffff", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
highcharts.js
.SH FILES
.PP
reportKit.dll
.PP
