.\" man page create by R# package system.
.TH HIGHCHARTS.JS 1 2000-1月 "barchart" "barchart"
.SH NAME
barchart \- It is a column char actually
.SH SYNOPSIS
\fIbarchart(\fBdata\fR as list, 
\fBtitle\fR as string = "title", 
\fBsubtitle\fR as string = "subtitle", 
\fBylab\fR as string = "Y", 
\fBserialName\fR as string = "data", 
\fBbackgroundColor\fR as any = "#ffffff", 
\fBdisplay3D\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
It is a column char actually
.PP
.SH OPTIONS
.PP
\fBdata\fB \fR\- 
 a dictionary of [name => value] tuple paired list
. 
.PP
.PP
\fBtitle\fB \fR\- -. 
.PP
.PP
\fBsubtitle\fB \fR\- -. 
.PP
.PP
\fBylab\fB \fR\- -. 
.PP
.PP
\fBserialName\fB \fR\- -. 
.PP
.PP
\fBbackgroundColor\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
highcharts.js
.SH FILES
.PP
reportKit.dll
.PP
