.\" man page create by R# package system.
.TH HIGHCHARTS.JS 1 2000-Jan "to_javascript" "to_javascript"
.SH NAME
to_javascript \- 
.SH SYNOPSIS
\fIto_javascript(\fBchart\fR as any, 
\fBdivId\fR as any = CALL "RANDOM_STR"(8), 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
highcharts.js
.SH FILES
.PP
reportKit.dll
.PP
