.\" man page create by R# package system.
.TH HIGHCHARTS.JS 1 2000-1月 "varywide_barChart" "varywide_barChart"
.SH NAME
varywide_barChart \- 
.SH SYNOPSIS
\fIvarywide_barChart(\fBdata\fR as list, 
\fBtitle\fR as string = "title", 
\fBsubtitle\fR as string = "subtitle", 
\fBxlab\fR as string = "X", 
\fBylab\fR as string = "Y", 
\fBserialName\fR as string = "data", 
\fBbackgroundColor\fR as any = "#ffffff", 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBdata\fB \fR\- 
 data mapping of \fB[name -> x, y]\fR
. 
.PP
.PP
\fBtitle\fB \fR\- -. 
.PP
.PP
\fBsubtitle\fB \fR\- -. 
.PP
.PP
\fBxlab\fB \fR\- -. 
.PP
.PP
\fBylab\fB \fR\- -. 
.PP
.PP
\fBserialName\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
highcharts.js
.SH FILES
.PP
reportKit.dll
.PP
