.\" man page create by R# package system.
.TH HIGHCHARTS.JS 1 2000-01-01 "varywide_pieChart" "varywide_pieChart"
.SH NAME
varywide_pieChart \- 
.SH SYNOPSIS
\fIvarywide_pieChart(\fBdata\fR as <generic> dataframe, 
\fBinnerSize\fR as string = "20", 
\fBtitle\fR as string = "pie chart", 
\fBsubtitle\fR as string = "pie chart", 
\fBpointerName\fR as string = "item", 
\fBserialName\fR as string = "serial name", 
\fBbackgroundColor\fR as any = "#ffffff");\fR
.SH OPTIONS
.PP
\fBdata\fB \fR\- -. 
.PP
.PP
\fBinnerSize\fB \fR\- radius size in percentage.. 
.PP
.PP
\fBtitle$\fB \fR\- -. 
.PP
.PP
\fBsubtitle$\fB \fR\- -. 
.PP
.PP
\fBpointerName$\fB \fR\- -. 
.PP
.PP
\fBserialName$\fB \fR\- -. 
.PP
.SH SEE ALSO
highcharts.js
.SH FILES
.PP
reportKit.dll
.PP
