.\" man page create by R# package system.
.TH HTML 4 2000-01-01 "reportTemplate" "reportTemplate"
.SH NAME
reportTemplate \- Create a html template model from a
.SH SYNOPSIS
\fIreportTemplate(\fBtemplate\fR as string, 
\fBcopyToTemp\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
Create a html template model from a 
 given report template directory.
.PP
.SH OPTIONS
.PP
\fBtemplate\fB \fR\- -. 
.PP
.SH SEE ALSO
html
.SH FILES
.PP
reportKit.dll
.PP
