#Region "Microsoft.VisualBasic::0dbc1e35b3e4b517fb6f41521f50efe1, G:/GCModeller/src/runtime/markdown2pdf/src/ReportBuilder//My Project/Resources.Designer.vb"

    ' Author:
    ' 
    '       xieguigang (I@xieguigang.me)
    ' 
    ' Copyright (c) 2021 R# language
    ' 
    ' 
    ' MIT License
    ' 
    ' 
    ' Permission is hereby granted, free of charge, to any person obtaining a copy
    ' of this software and associated documentation files (the "Software"), to deal
    ' in the Software without restriction, including without limitation the rights
    ' to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    ' copies of the Software, and to permit persons to whom the Software is
    ' furnished to do so, subject to the following conditions:
    ' 
    ' The above copyright notice and this permission notice shall be included in all
    ' copies or substantial portions of the Software.
    ' 
    ' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    ' IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    ' FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    ' AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    ' LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    ' OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    ' SOFTWARE.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 132
    '    Code Lines: 53
    ' Comment Lines: 67
    '   Blank Lines: 12
    '     File Size: 6.41 KB


    '     Module Resources
    ' 
    '         Properties: Culture, DNA, foundation, index, readmail
    '                     ResourceManager
    ' 
    ' 
    ' /********************************************************************************/

#End Region

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SMRUCC.genomics.GCModeller.Workbench.ReportBuilder.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property

        '''<summary>
        '''  Looks up a localized string similar to meta.foundation-version {
        '''  font-family: &quot;/5.4.5/&quot;; }
        '''
        '''meta.foundation-mq-small {
        '''  font-family: &quot;/only screen/&quot;;
        '''  width: 0em; }
        '''
        '''meta.foundation-mq-medium {
        '''  font-family: &quot;/only screen and (min-width:40.063em)/&quot;;
        '''  width: 40.063em; }
        '''
        '''meta.foundation-mq-large {
        '''  font-family: &quot;/only screen and (min-width:64.063em)/&quot;;
        '''  width: 64.063em; }
        '''
        '''meta.foundation-mq-xlarge {
        '''  font-family: &quot;/only screen and (min-width:90.063em)/&quot;;
        '''  width: 90.063em; }
        '''
        '''meta.foundation-mq-xxlarge {
        '''  font-family: &quot;/only screen and [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property foundation() As String
            Get
                Return ResourceManager.GetString("foundation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;!-- saved from url=(0052)http://foundation.zurb.com/templates/workspace.html# --&gt;
        '''&lt;html class=&quot; js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionsto [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property index() As String
            Get
                Return ResourceManager.GetString("index", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        '''&lt;html lang=&quot;en&quot;&gt;
        '''&lt;head&gt;
        '''    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=US-ASCII&quot;&gt;
        '''    &lt;title&gt;[GCModeller] {Title}.&lt;/title&gt;
        '''&lt;/head&gt;
        '''&lt;body topmargin=&quot;0&quot;
        '''      leftmargin=&quot;0&quot;
        '''      marginheight=&quot;0&quot;
        '''      marginwidth=&quot;0&quot;
        '''      style=&quot;-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background: #fafafa; color: #222222; font-family: &apos;Helvetica&apos;, &apos;Arial&apos;, sans-serif; font-size: 14px; f [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property readmail() As String
            Get
                Return ResourceManager.GetString("readmail", resourceCulture)
            End Get
        End Property
    End Module
End Namespace

