.\" man page create by R# package system.
.TH PDF 4 2000-01-01 "convertWmf" "convertWmf"
.SH NAME
convertWmf \- convert wmf image to pdf file
.SH SYNOPSIS
\fIconvertWmf(\fBwmf\fR as string, 
\fBpdfsave\fR as string);\fR
.SH DESCRIPTION
.PP
convert wmf image to pdf file
.PP
.SH OPTIONS
.PP
\fBwmf\fB \fR\- -. 
.PP
.PP
\fBpdfsave\fB \fR\- -. 
.PP
.SH SEE ALSO
pdf
.SH FILES
.PP
reportKit.dll
.PP
