.\" man page create by R# package system.
.TH PDF 4 2000-01-01 "pdfDecoration" "pdfDecoration"
.SH NAME
pdfDecoration \- 
.SH SYNOPSIS
\fIpdfDecoration(\fBspacing\fR as double = 8, 
\fBcenter\fR as string = "-- [page] --", 
\fBfontsize\fR as double = 14, 
\fBfontname\fR as string = "Microsoft YaHei", 
\fBhtml\fR as string = \fB<NULL>\fR);\fR
.SH OPTIONS
.PP
\fBspacing\fB \fR\- -. 
.PP
.PP
\fBcenter\fB \fR\- -. 
.PP
.PP
\fBfontsize\fB \fR\- -. 
.PP
.PP
\fBfontname\fB \fR\- -. 
.PP
.PP
\fBhtml\fB \fR\- Adds a html footer/header. 
.PP
.SH SEE ALSO
pdf
.SH FILES
.PP
reportKit.dll
.PP
