.\" man page create by R# package system.
.TH PDF 4 2000-Jan "pdfGlobal_options" "pdfGlobal_options"
.SH NAME
pdfGlobal_options \- 
.SH SYNOPSIS
\fIpdfGlobal_options(\fBmargintop\fR as integer = 0, 
\fBmarginleft\fR as integer = 0, 
\fBmarginright\fR as integer = 0, 
\fBmarginbottom\fR as integer = 0, 
\fBimagequality\fR as integer = 100, 
\fBtitle\fR as string = "", 
\fBorientation\fR as <integer> Orientations = \fB<NULL>\fR);\fR
.SH SEE ALSO
pdf
.SH FILES
.PP
reportKit.dll
.PP
