.\" man page create by R# package system.
.TH PDF 4 2000-1月 "pdfPage_options" "pdfPage_options"
.SH NAME
pdfPage_options \- 
.SH SYNOPSIS
\fIpdfPage_options(\fBjavascriptdelay\fR as double = 3000, 
\fBloaderrorhandling\fR as <integer> handlers = [abort], 
\fBdebugjavascript\fR as boolean = TRUE, 
\fBenableforms\fR as boolean = TRUE);\fR
.SH SEE ALSO
pdf
.SH FILES
.PP
reportKit.dll
.PP
